gitea_image: gitea/gitea:latest
gitea_container_name: gitea
gitea_ports:
  - "3000:3000"
  - "{{ gitea_ssh_port }}:22"
gitea_volumes:
  - gitea_data:/data
  - /etc/timezone:/etc/timezone:ro
  - /etc/localtime:/etc/localtime:ro
gitea_env:
  GITEA__database__DB_TYPE: postgres
  GITEA__database__HOST: postgres_db:5432
  GITEA__database__NAME: "{{ gitea_db }}"
  GITEA__database__USER: "{{ gitea_db_user }}"
  GITEA__database__PASSWD: "{{ gitea_password }}"
  GITEA__server__DOMAIN: "{{ gitea_domain }}"
  GITEA__server__ROOT_URL: "https://{{ gitea_domain }}/"
  GITEA__server__SSH_DOMAIN: "{{ ansible_host }}"
  GITEA__server__SSH_PORT: "{{ gitea_ssh_port }}"
  GITEA__security__SECRET_KEY: "{{ gitea_secret_key }}"
gitea_labels:
  traefik.enable: "true"
  traefik.http.routers.gitea.rule: "Host(`{{ gitea_domain }}`)"
  traefik.http.services.gitea.loadbalancer.server.port: "3000"
