---
portainer_image: portainer/portainer-ce:latest
portainer_agent_image: portainer/agent:latest
portainer_ports:
  - "8000:8000"
  - "9443:9443"
portainer_agent_ports:
  - "9001:9001"
portainer_agent_volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /var/lib/docker/volumes:/var/lib/docker/volumes
  - /:/host
portainer_data_volume: portainer_data:/data
