---
- name: Pull pgAdmin Docker image
  docker_image:
    name: "{{ pgadmin_image }}"
    source: pull

- name: Create pgAdmin container
  docker_container:
    name: "{{ pgadmin_container_name }}"
    image: "{{ pgadmin_image }}"
    state: started
    restart_policy: always
    env: "{{ pgadmin_env }}"
    ports: "{{ pgadmin_ports }}"
    volumes: "{{ pgadmin_volumes }}"
    labels: "{{ pgadmin_labels }}"
