---
- name: Stop any running Node Exporter container
  shell: |
    docker ps -q --filter "ancestor=quay.io/prometheus/node-exporter" | xargs -r docker stop
  ignore_errors: true

- name: Remove any Node Exporter container
  shell: |
    docker ps -a -q --filter "ancestor=quay.io/prometheus/node-exporter" | xargs -r docker rm
  ignore_errors: true
