---
- name: Create MLflow directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ mlflow_directories }}"

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Log into Gitea registry
  docker_login:
    registry: "{{ gitea_registry }}"
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"

- name: Pull MLflow Docker image from Gitea registry
  docker_image:
    name: "{{ mlflow_image }}"
    source: pull

- name: Create MLflow Docker container
  docker_container:
    name: "{{ mlflow_container_name }}"
    image: "{{ mlflow_image }}"
    state: started
    restart_policy: always
    ports: "{{ mlflow_ports }}"
    env: "{{ mlflow_env }}"
    volumes: "{{ mlflow_volumes }}"
